/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers';
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from '@ethersproject/contracts';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';

interface LondonBurnPristineInterface extends ethers.utils.Interface {
  functions: {
    '_mintTokenType(uint256,tuple[])': FunctionFragment;
    'approve(address,uint256)': FunctionFragment;
    'balanceOf(address)': FunctionFragment;
    'contractURI()': FunctionFragment;
    'externalBurnableERC721()': FunctionFragment;
    'getApproved(uint256)': FunctionFragment;
    'getMintCheckHash(tuple)': FunctionFragment;
    'isApprovedForAll(address,address)': FunctionFragment;
    'isSigned(address,bytes32,uint8,bytes32,bytes32)': FunctionFragment;
    'mintPristineType(tuple[])': FunctionFragment;
    'mintingAuthority()': FunctionFragment;
    'name()': FunctionFragment;
    'owner()': FunctionFragment;
    'ownerOf(uint256)': FunctionFragment;
    'payableErc20()': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'revealBlockNumber()': FunctionFragment;
    'safeTransferFrom(address,address,uint256)': FunctionFragment;
    'setApprovalForAll(address,bool)': FunctionFragment;
    'setContractURI(string)': FunctionFragment;
    'setMintingAuthority(address)': FunctionFragment;
    'setRevealBlockNumber(uint256)': FunctionFragment;
    'setTreasury(address)': FunctionFragment;
    'setUltraSonicForkBlockNumber(uint256)': FunctionFragment;
    'splitSignature(bytes)': FunctionFragment;
    'supportsInterface(bytes4)': FunctionFragment;
    'symbol()': FunctionFragment;
    'tokenTypeSupply(uint256)': FunctionFragment;
    'tokenURI(uint256)': FunctionFragment;
    'transferFrom(address,address,uint256)': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'treasury()': FunctionFragment;
    'ultraSonicForkBlockNumber()': FunctionFragment;
    'verifyMintCheck(tuple)': FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: '_mintTokenType',
    values: [BigNumberish, { to: string; URI: string; signature: BytesLike }[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'approve',
    values: [string, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'balanceOf', values: [string]): string;
  encodeFunctionData(
    functionFragment: 'contractURI',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'externalBurnableERC721',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getApproved',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'getMintCheckHash',
    values: [{ to: string; URI: string; signature: BytesLike }],
  ): string;
  encodeFunctionData(
    functionFragment: 'isApprovedForAll',
    values: [string, string],
  ): string;
  encodeFunctionData(
    functionFragment: 'isSigned',
    values: [string, BytesLike, BigNumberish, BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintPristineType',
    values: [{ to: string; URI: string; signature: BytesLike }[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintingAuthority',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'name', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'ownerOf',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'payableErc20',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'revealBlockNumber',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'safeTransferFrom',
    values: [string, string, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'setApprovalForAll',
    values: [string, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'setContractURI',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'setMintingAuthority',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'setRevealBlockNumber',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'setTreasury', values: [string]): string;
  encodeFunctionData(
    functionFragment: 'setUltraSonicForkBlockNumber',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'splitSignature',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'supportsInterface',
    values: [BytesLike],
  ): string;
  encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'tokenTypeSupply',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'tokenURI',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'transferFrom',
    values: [string, string, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string],
  ): string;
  encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'ultraSonicForkBlockNumber',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'verifyMintCheck',
    values: [{ to: string; URI: string; signature: BytesLike }],
  ): string;

  decodeFunctionResult(
    functionFragment: '_mintTokenType',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'contractURI',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'externalBurnableERC721',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getApproved',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getMintCheckHash',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isApprovedForAll',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'isSigned', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'mintPristineType',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'mintingAuthority',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'payableErc20',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'revealBlockNumber',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'safeTransferFrom',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setApprovalForAll',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setContractURI',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setMintingAuthority',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setRevealBlockNumber',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setTreasury',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setUltraSonicForkBlockNumber',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'splitSignature',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'supportsInterface',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'tokenTypeSupply',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'transferFrom',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'ultraSonicForkBlockNumber',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'verifyMintCheck',
    data: BytesLike,
  ): Result;

  events: {
    'Approval(address,address,uint256)': EventFragment;
    'ApprovalForAll(address,address,bool)': EventFragment;
    'MintCheckUsed(uint256,bytes32)': EventFragment;
    'OwnershipTransferred(address,address)': EventFragment;
    'Transfer(address,address,uint256)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'Approval'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ApprovalForAll'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'MintCheckUsed'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Transfer'): EventFragment;
}

export class LondonBurnPristine extends Contract {
  'connect'(signerOrProvider: Signer | Provider | string): this;
  'attach'(addressOrName: string): this;
  'deployed'(): Promise<this>;

  'on'(event: EventFilter | string, listener: Listener): this;
  'once'(event: EventFilter | string, listener: Listener): this;
  'addListener'(eventName: EventFilter | string, listener: Listener): this;
  'removeAllListeners'(eventName: EventFilter | string): this;
  'removeListener'(eventName: any, listener: Listener): this;

  'interface': LondonBurnPristineInterface;

  'functions': {
    _mintTokenType(
      tokenType: BigNumberish,
      _mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    '_mintTokenType(uint256,tuple[])'(
      tokenType: BigNumberish,
      _mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'approve(address,uint256)'(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    'balanceOf(address)'(
      owner: string,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    contractURI(overrides?: CallOverrides): Promise<[string]>;

    'contractURI()'(overrides?: CallOverrides): Promise<[string]>;

    externalBurnableERC721(overrides?: CallOverrides): Promise<[string]>;

    'externalBurnableERC721()'(overrides?: CallOverrides): Promise<[string]>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    'getApproved(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    getMintCheckHash(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<[string]>;

    'getMintCheckHash((address,string,bytes))'(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<[string]>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    'isApprovedForAll(address,address)'(
      owner: string,
      operator: string,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    isSigned(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    'isSigned(address,bytes32,uint8,bytes32,bytes32)'(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    mintPristineType(
      mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'mintPristineType(tuple[])'(
      mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    mintingAuthority(overrides?: CallOverrides): Promise<[string]>;

    'mintingAuthority()'(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    'name()'(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    'owner()'(overrides?: CallOverrides): Promise<[string]>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    'ownerOf(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    payableErc20(overrides?: CallOverrides): Promise<[string]>;

    'payableErc20()'(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>;

    revealBlockNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    'revealBlockNumber()'(overrides?: CallOverrides): Promise<[BigNumber]>;

    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'setApprovalForAll(address,bool)'(
      operator: string,
      approved: boolean,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    setContractURI(
      newContractURI: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'setContractURI(string)'(
      newContractURI: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    setMintingAuthority(
      _mintingAuthority: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'setMintingAuthority(address)'(
      _mintingAuthority: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    setRevealBlockNumber(
      _revealBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'setRevealBlockNumber(uint256)'(
      _revealBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    setTreasury(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'setTreasury(address)'(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    setUltraSonicForkBlockNumber(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'setUltraSonicForkBlockNumber(uint256)'(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    splitSignature(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string, string, number] & { r: string; s: string; v: number }>;

    'splitSignature(bytes)'(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string, string, number] & { r: string; s: string; v: number }>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    'supportsInterface(bytes4)'(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    'symbol()'(overrides?: CallOverrides): Promise<[string]>;

    tokenTypeSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    'tokenTypeSupply(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    'tokenURI(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'transferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    treasury(overrides?: CallOverrides): Promise<[string]>;

    'treasury()'(overrides?: CallOverrides): Promise<[string]>;

    ultraSonicForkBlockNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    'ultraSonicForkBlockNumber()'(
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    verifyMintCheck(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    'verifyMintCheck((address,string,bytes))'(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<[boolean]>;
  };

  '_mintTokenType'(
    tokenType: BigNumberish,
    _mintChecks: { to: string; URI: string; signature: BytesLike }[],
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  '_mintTokenType(uint256,tuple[])'(
    tokenType: BigNumberish,
    _mintChecks: { to: string; URI: string; signature: BytesLike }[],
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'approve'(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'approve(address,uint256)'(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'balanceOf'(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  'balanceOf(address)'(
    owner: string,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  'contractURI'(overrides?: CallOverrides): Promise<string>;

  'contractURI()'(overrides?: CallOverrides): Promise<string>;

  'externalBurnableERC721'(overrides?: CallOverrides): Promise<string>;

  'externalBurnableERC721()'(overrides?: CallOverrides): Promise<string>;

  'getApproved'(
    tokenId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  'getApproved(uint256)'(
    tokenId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  'getMintCheckHash'(
    _mintCheck: { to: string; URI: string; signature: BytesLike },
    overrides?: CallOverrides,
  ): Promise<string>;

  'getMintCheckHash((address,string,bytes))'(
    _mintCheck: { to: string; URI: string; signature: BytesLike },
    overrides?: CallOverrides,
  ): Promise<string>;

  'isApprovedForAll'(
    owner: string,
    operator: string,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  'isApprovedForAll(address,address)'(
    owner: string,
    operator: string,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  'isSigned'(
    _address: string,
    messageHash: BytesLike,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  'isSigned(address,bytes32,uint8,bytes32,bytes32)'(
    _address: string,
    messageHash: BytesLike,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  'mintPristineType'(
    mintChecks: { to: string; URI: string; signature: BytesLike }[],
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'mintPristineType(tuple[])'(
    mintChecks: { to: string; URI: string; signature: BytesLike }[],
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'mintingAuthority'(overrides?: CallOverrides): Promise<string>;

  'mintingAuthority()'(overrides?: CallOverrides): Promise<string>;

  'name'(overrides?: CallOverrides): Promise<string>;

  'name()'(overrides?: CallOverrides): Promise<string>;

  'owner'(overrides?: CallOverrides): Promise<string>;

  'owner()'(overrides?: CallOverrides): Promise<string>;

  'ownerOf'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  'ownerOf(uint256)'(
    tokenId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  'payableErc20'(overrides?: CallOverrides): Promise<string>;

  'payableErc20()'(overrides?: CallOverrides): Promise<string>;

  'renounceOwnership'(overrides?: Overrides): Promise<ContractTransaction>;

  'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>;

  'revealBlockNumber'(overrides?: CallOverrides): Promise<BigNumber>;

  'revealBlockNumber()'(overrides?: CallOverrides): Promise<BigNumber>;

  'safeTransferFrom(address,address,uint256)'(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'safeTransferFrom(address,address,uint256,bytes)'(
    from: string,
    to: string,
    tokenId: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setApprovalForAll'(
    operator: string,
    approved: boolean,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setApprovalForAll(address,bool)'(
    operator: string,
    approved: boolean,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setContractURI'(
    newContractURI: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setContractURI(string)'(
    newContractURI: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setMintingAuthority'(
    _mintingAuthority: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setMintingAuthority(address)'(
    _mintingAuthority: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setRevealBlockNumber'(
    _revealBlockNumber: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setRevealBlockNumber(uint256)'(
    _revealBlockNumber: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setTreasury'(
    _treasury: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setTreasury(address)'(
    _treasury: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setUltraSonicForkBlockNumber'(
    _ultraSonicForkBlockNumber: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setUltraSonicForkBlockNumber(uint256)'(
    _ultraSonicForkBlockNumber: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'splitSignature'(
    sig: BytesLike,
    overrides?: CallOverrides,
  ): Promise<[string, string, number] & { r: string; s: string; v: number }>;

  'splitSignature(bytes)'(
    sig: BytesLike,
    overrides?: CallOverrides,
  ): Promise<[string, string, number] & { r: string; s: string; v: number }>;

  'supportsInterface'(
    interfaceId: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  'supportsInterface(bytes4)'(
    interfaceId: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  'symbol'(overrides?: CallOverrides): Promise<string>;

  'symbol()'(overrides?: CallOverrides): Promise<string>;

  'tokenTypeSupply'(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  'tokenTypeSupply(uint256)'(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  'tokenURI'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  'tokenURI(uint256)'(
    tokenId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  'transferFrom'(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'transferFrom(address,address,uint256)'(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'transferOwnership'(
    newOwner: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'transferOwnership(address)'(
    newOwner: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'treasury'(overrides?: CallOverrides): Promise<string>;

  'treasury()'(overrides?: CallOverrides): Promise<string>;

  'ultraSonicForkBlockNumber'(overrides?: CallOverrides): Promise<BigNumber>;

  'ultraSonicForkBlockNumber()'(overrides?: CallOverrides): Promise<BigNumber>;

  'verifyMintCheck'(
    _mintCheck: { to: string; URI: string; signature: BytesLike },
    overrides?: CallOverrides,
  ): Promise<boolean>;

  'verifyMintCheck((address,string,bytes))'(
    _mintCheck: { to: string; URI: string; signature: BytesLike },
    overrides?: CallOverrides,
  ): Promise<boolean>;

  'callStatic': {
    _mintTokenType(
      tokenType: BigNumberish,
      _mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: CallOverrides,
    ): Promise<void>;

    '_mintTokenType(uint256,tuple[])'(
      tokenType: BigNumberish,
      _mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: CallOverrides,
    ): Promise<void>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    'approve(address,uint256)'(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    'balanceOf(address)'(
      owner: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    contractURI(overrides?: CallOverrides): Promise<string>;

    'contractURI()'(overrides?: CallOverrides): Promise<string>;

    externalBurnableERC721(overrides?: CallOverrides): Promise<string>;

    'externalBurnableERC721()'(overrides?: CallOverrides): Promise<string>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    'getApproved(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    getMintCheckHash(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<string>;

    'getMintCheckHash((address,string,bytes))'(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<string>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    'isApprovedForAll(address,address)'(
      owner: string,
      operator: string,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    isSigned(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    'isSigned(address,bytes32,uint8,bytes32,bytes32)'(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    mintPristineType(
      mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: CallOverrides,
    ): Promise<void>;

    'mintPristineType(tuple[])'(
      mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: CallOverrides,
    ): Promise<void>;

    mintingAuthority(overrides?: CallOverrides): Promise<string>;

    'mintingAuthority()'(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    'name()'(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    'owner()'(overrides?: CallOverrides): Promise<string>;

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    'ownerOf(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    payableErc20(overrides?: CallOverrides): Promise<string>;

    'payableErc20()'(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    'renounceOwnership()'(overrides?: CallOverrides): Promise<void>;

    revealBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    'revealBlockNumber()'(overrides?: CallOverrides): Promise<BigNumber>;

    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides,
    ): Promise<void>;

    'setApprovalForAll(address,bool)'(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides,
    ): Promise<void>;

    setContractURI(
      newContractURI: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    'setContractURI(string)'(
      newContractURI: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    setMintingAuthority(
      _mintingAuthority: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    'setMintingAuthority(address)'(
      _mintingAuthority: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    setRevealBlockNumber(
      _revealBlockNumber: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    'setRevealBlockNumber(uint256)'(
      _revealBlockNumber: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    setTreasury(_treasury: string, overrides?: CallOverrides): Promise<void>;

    'setTreasury(address)'(
      _treasury: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    setUltraSonicForkBlockNumber(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    'setUltraSonicForkBlockNumber(uint256)'(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    splitSignature(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string, string, number] & { r: string; s: string; v: number }>;

    'splitSignature(bytes)'(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string, string, number] & { r: string; s: string; v: number }>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    'supportsInterface(bytes4)'(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    'symbol()'(overrides?: CallOverrides): Promise<string>;

    tokenTypeSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'tokenTypeSupply(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    'tokenURI(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    'transferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    treasury(overrides?: CallOverrides): Promise<string>;

    'treasury()'(overrides?: CallOverrides): Promise<string>;

    ultraSonicForkBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    'ultraSonicForkBlockNumber()'(
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    verifyMintCheck(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<boolean>;

    'verifyMintCheck((address,string,bytes))'(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<boolean>;
  };

  'filters': {
    Approval(
      owner: string | null,
      approved: string | null,
      tokenId: BigNumberish | null,
    ): EventFilter;

    ApprovalForAll(
      owner: string | null,
      operator: string | null,
      approved: null,
    ): EventFilter;

    MintCheckUsed(
      tokenId: BigNumberish | null,
      mintCheck: BytesLike | null,
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null,
    ): EventFilter;

    Transfer(
      from: string | null,
      to: string | null,
      tokenId: BigNumberish | null,
    ): EventFilter;
  };

  'estimateGas': {
    _mintTokenType(
      tokenType: BigNumberish,
      _mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<BigNumber>;

    '_mintTokenType(uint256,tuple[])'(
      tokenType: BigNumberish,
      _mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<BigNumber>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'approve(address,uint256)'(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    'balanceOf(address)'(
      owner: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    contractURI(overrides?: CallOverrides): Promise<BigNumber>;

    'contractURI()'(overrides?: CallOverrides): Promise<BigNumber>;

    externalBurnableERC721(overrides?: CallOverrides): Promise<BigNumber>;

    'externalBurnableERC721()'(overrides?: CallOverrides): Promise<BigNumber>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'getApproved(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getMintCheckHash(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'getMintCheckHash((address,string,bytes))'(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'isApprovedForAll(address,address)'(
      owner: string,
      operator: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isSigned(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'isSigned(address,bytes32,uint8,bytes32,bytes32)'(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    mintPristineType(
      mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'mintPristineType(tuple[])'(
      mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<BigNumber>;

    mintingAuthority(overrides?: CallOverrides): Promise<BigNumber>;

    'mintingAuthority()'(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    'name()'(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    'owner()'(overrides?: CallOverrides): Promise<BigNumber>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'ownerOf(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    payableErc20(overrides?: CallOverrides): Promise<BigNumber>;

    'payableErc20()'(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    'renounceOwnership()'(overrides?: Overrides): Promise<BigNumber>;

    revealBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    'revealBlockNumber()'(overrides?: CallOverrides): Promise<BigNumber>;

    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'setApprovalForAll(address,bool)'(
      operator: string,
      approved: boolean,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    setContractURI(
      newContractURI: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'setContractURI(string)'(
      newContractURI: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    setMintingAuthority(
      _mintingAuthority: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'setMintingAuthority(address)'(
      _mintingAuthority: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    setRevealBlockNumber(
      _revealBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'setRevealBlockNumber(uint256)'(
      _revealBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    setTreasury(_treasury: string, overrides?: Overrides): Promise<BigNumber>;

    'setTreasury(address)'(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    setUltraSonicForkBlockNumber(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'setUltraSonicForkBlockNumber(uint256)'(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    splitSignature(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'splitSignature(bytes)'(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'supportsInterface(bytes4)'(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    'symbol()'(overrides?: CallOverrides): Promise<BigNumber>;

    tokenTypeSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'tokenTypeSupply(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'tokenURI(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'transferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    'treasury()'(overrides?: CallOverrides): Promise<BigNumber>;

    ultraSonicForkBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    'ultraSonicForkBlockNumber()'(
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    verifyMintCheck(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'verifyMintCheck((address,string,bytes))'(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  'populateTransaction': {
    _mintTokenType(
      tokenType: BigNumberish,
      _mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    '_mintTokenType(uint256,tuple[])'(
      tokenType: BigNumberish,
      _mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'approve(address,uint256)'(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'balanceOf(address)'(
      owner: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    contractURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'contractURI()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    externalBurnableERC721(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'externalBurnableERC721()'(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'getApproved(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getMintCheckHash(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'getMintCheckHash((address,string,bytes))'(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'isApprovedForAll(address,address)'(
      owner: string,
      operator: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isSigned(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'isSigned(address,bytes32,uint8,bytes32,bytes32)'(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    mintPristineType(
      mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'mintPristineType(tuple[])'(
      mintChecks: { to: string; URI: string; signature: BytesLike }[],
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    mintingAuthority(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'mintingAuthority()'(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'name()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'owner()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'ownerOf(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    payableErc20(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'payableErc20()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    'renounceOwnership()'(overrides?: Overrides): Promise<PopulatedTransaction>;

    revealBlockNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'revealBlockNumber()'(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'setApprovalForAll(address,bool)'(
      operator: string,
      approved: boolean,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    setContractURI(
      newContractURI: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'setContractURI(string)'(
      newContractURI: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    setMintingAuthority(
      _mintingAuthority: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'setMintingAuthority(address)'(
      _mintingAuthority: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    setRevealBlockNumber(
      _revealBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'setRevealBlockNumber(uint256)'(
      _revealBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    setTreasury(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'setTreasury(address)'(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    setUltraSonicForkBlockNumber(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'setUltraSonicForkBlockNumber(uint256)'(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    splitSignature(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'splitSignature(bytes)'(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'supportsInterface(bytes4)'(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'symbol()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenTypeSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'tokenTypeSupply(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'tokenURI(uint256)'(
      tokenId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'transferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'treasury()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ultraSonicForkBlockNumber(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'ultraSonicForkBlockNumber()'(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    verifyMintCheck(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'verifyMintCheck((address,string,bytes))'(
      _mintCheck: { to: string; URI: string; signature: BytesLike },
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
