/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import { Listener, Provider } from '@ethersproject/providers';
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common';

export type MintCheckStruct = { to: string; URI: string; signature: BytesLike };

export type MintCheckStructOutput = [string, string, string] & {
  to: string;
  URI: string;
  signature: string;
};

export interface LondonBurnMinterInterface extends utils.Interface {
  functions: {
    'airdropAuthority()': FunctionFragment;
    'externalBurnableERC721()': FunctionFragment;
    'getAirdropHash(address,uint8)': FunctionFragment;
    'isSigned(address,bytes32,uint8,bytes32,bytes32)': FunctionFragment;
    'londonBurn()': FunctionFragment;
    'londonNeededFromGiftAmount(uint256)': FunctionFragment;
    'londonNeededFromSelfAmount(uint256)': FunctionFragment;
    'mintAshenType(uint256[],(address,string,bytes)[])': FunctionFragment;
    'mintEternalType((address,string,bytes)[])': FunctionFragment;
    'mintGiftType(uint256[],(address,string,bytes)[])': FunctionFragment;
    'mintNobleType(uint8,bytes,(address,string,bytes)[])': FunctionFragment;
    'mintPristineType((address,string,bytes)[])': FunctionFragment;
    'numBurnFromGiftAmount(uint256)': FunctionFragment;
    'numBurnFromSelfAmount(uint256)': FunctionFragment;
    'owner()': FunctionFragment;
    'payableErc20()': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'revealBlockNumber()': FunctionFragment;
    'setAirdropAuthority(address)': FunctionFragment;
    'setRevealBlockNumber(uint256)': FunctionFragment;
    'setTreasury(address)': FunctionFragment;
    'setUltraSonicForkBlockNumber(uint256)': FunctionFragment;
    'splitSignature(bytes)': FunctionFragment;
    'sushiswap()': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'treasury()': FunctionFragment;
    'ultraSonicForkBlockNumber()': FunctionFragment;
    'verifyAirdrop(address,uint8,bytes)': FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'airdropAuthority',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'externalBurnableERC721',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getAirdropHash',
    values: [string, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'isSigned',
    values: [string, BytesLike, BigNumberish, BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'londonBurn',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'londonNeededFromGiftAmount',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'londonNeededFromSelfAmount',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintAshenType',
    values: [BigNumberish[], MintCheckStruct[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintEternalType',
    values: [MintCheckStruct[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintGiftType',
    values: [BigNumberish[], MintCheckStruct[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintNobleType',
    values: [BigNumberish, BytesLike, MintCheckStruct[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintPristineType',
    values: [MintCheckStruct[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'numBurnFromGiftAmount',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'numBurnFromSelfAmount',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'payableErc20',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'revealBlockNumber',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'setAirdropAuthority',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'setRevealBlockNumber',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'setTreasury', values: [string]): string;
  encodeFunctionData(
    functionFragment: 'setUltraSonicForkBlockNumber',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'splitSignature',
    values: [BytesLike],
  ): string;
  encodeFunctionData(functionFragment: 'sushiswap', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string],
  ): string;
  encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'ultraSonicForkBlockNumber',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'verifyAirdrop',
    values: [string, BigNumberish, BytesLike],
  ): string;

  decodeFunctionResult(
    functionFragment: 'airdropAuthority',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'externalBurnableERC721',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getAirdropHash',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'isSigned', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'londonBurn', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'londonNeededFromGiftAmount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'londonNeededFromSelfAmount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'mintAshenType',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'mintEternalType',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'mintGiftType',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'mintNobleType',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'mintPristineType',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'numBurnFromGiftAmount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'numBurnFromSelfAmount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'payableErc20',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'revealBlockNumber',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setAirdropAuthority',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setRevealBlockNumber',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setTreasury',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setUltraSonicForkBlockNumber',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'splitSignature',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'sushiswap', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'ultraSonicForkBlockNumber',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'verifyAirdrop',
    data: BytesLike,
  ): Result;

  events: {
    'OwnershipTransferred(address,address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface LondonBurnMinter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LondonBurnMinterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    airdropAuthority(overrides?: CallOverrides): Promise<[string]>;

    externalBurnableERC721(overrides?: CallOverrides): Promise<[string]>;

    getAirdropHash(
      to: string,
      nobility: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    isSigned(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    londonBurn(overrides?: CallOverrides): Promise<[string]>;

    londonNeededFromGiftAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    londonNeededFromSelfAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    mintAshenType(
      tokenIds: BigNumberish[],
      _mintChecks: MintCheckStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    mintEternalType(
      _mintChecks: MintCheckStruct[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    mintGiftType(
      giftTokenIds: BigNumberish[],
      mintChecks: MintCheckStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    mintNobleType(
      nobility: BigNumberish,
      signature: BytesLike,
      mintChecks: MintCheckStruct[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    mintPristineType(
      mintChecks: MintCheckStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    numBurnFromGiftAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    numBurnFromSelfAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    payableErc20(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    revealBlockNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    setAirdropAuthority(
      _airdropAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setRevealBlockNumber(
      _revealBlockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setTreasury(
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setUltraSonicForkBlockNumber(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    splitSignature(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string, string, number] & { r: string; s: string; v: number }>;

    sushiswap(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    treasury(overrides?: CallOverrides): Promise<[string]>;

    ultraSonicForkBlockNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    verifyAirdrop(
      to: string,
      nobility: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;
  };

  airdropAuthority(overrides?: CallOverrides): Promise<string>;

  externalBurnableERC721(overrides?: CallOverrides): Promise<string>;

  getAirdropHash(
    to: string,
    nobility: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  isSigned(
    _address: string,
    messageHash: BytesLike,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  londonBurn(overrides?: CallOverrides): Promise<string>;

  londonNeededFromGiftAmount(
    amount: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  londonNeededFromSelfAmount(
    amount: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  mintAshenType(
    tokenIds: BigNumberish[],
    _mintChecks: MintCheckStruct[],
    overrides?: PayableOverrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  mintEternalType(
    _mintChecks: MintCheckStruct[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  mintGiftType(
    giftTokenIds: BigNumberish[],
    mintChecks: MintCheckStruct[],
    overrides?: PayableOverrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  mintNobleType(
    nobility: BigNumberish,
    signature: BytesLike,
    mintChecks: MintCheckStruct[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  mintPristineType(
    mintChecks: MintCheckStruct[],
    overrides?: PayableOverrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  numBurnFromGiftAmount(
    amount: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  numBurnFromSelfAmount(
    amount: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  payableErc20(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  revealBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

  setAirdropAuthority(
    _airdropAuthority: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setRevealBlockNumber(
    _revealBlockNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setTreasury(
    _treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setUltraSonicForkBlockNumber(
    _ultraSonicForkBlockNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  splitSignature(
    sig: BytesLike,
    overrides?: CallOverrides,
  ): Promise<[string, string, number] & { r: string; s: string; v: number }>;

  sushiswap(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  treasury(overrides?: CallOverrides): Promise<string>;

  ultraSonicForkBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

  verifyAirdrop(
    to: string,
    nobility: BigNumberish,
    signature: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  callStatic: {
    airdropAuthority(overrides?: CallOverrides): Promise<string>;

    externalBurnableERC721(overrides?: CallOverrides): Promise<string>;

    getAirdropHash(
      to: string,
      nobility: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    isSigned(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    londonBurn(overrides?: CallOverrides): Promise<string>;

    londonNeededFromGiftAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    londonNeededFromSelfAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    mintAshenType(
      tokenIds: BigNumberish[],
      _mintChecks: MintCheckStruct[],
      overrides?: CallOverrides,
    ): Promise<void>;

    mintEternalType(
      _mintChecks: MintCheckStruct[],
      overrides?: CallOverrides,
    ): Promise<void>;

    mintGiftType(
      giftTokenIds: BigNumberish[],
      mintChecks: MintCheckStruct[],
      overrides?: CallOverrides,
    ): Promise<void>;

    mintNobleType(
      nobility: BigNumberish,
      signature: BytesLike,
      mintChecks: MintCheckStruct[],
      overrides?: CallOverrides,
    ): Promise<void>;

    mintPristineType(
      mintChecks: MintCheckStruct[],
      overrides?: CallOverrides,
    ): Promise<void>;

    numBurnFromGiftAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    numBurnFromSelfAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    payableErc20(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    revealBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    setAirdropAuthority(
      _airdropAuthority: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    setRevealBlockNumber(
      _revealBlockNumber: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    setTreasury(_treasury: string, overrides?: CallOverrides): Promise<void>;

    setUltraSonicForkBlockNumber(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    splitSignature(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string, string, number] & { r: string; s: string; v: number }>;

    sushiswap(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    treasury(overrides?: CallOverrides): Promise<string>;

    ultraSonicForkBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    verifyAirdrop(
      to: string,
      nobility: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;
  };

  filters: {
    'OwnershipTransferred(address,address)'(
      previousOwner?: string | null,
      newOwner?: string | null,
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null,
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    airdropAuthority(overrides?: CallOverrides): Promise<BigNumber>;

    externalBurnableERC721(overrides?: CallOverrides): Promise<BigNumber>;

    getAirdropHash(
      to: string,
      nobility: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isSigned(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    londonBurn(overrides?: CallOverrides): Promise<BigNumber>;

    londonNeededFromGiftAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    londonNeededFromSelfAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    mintAshenType(
      tokenIds: BigNumberish[],
      _mintChecks: MintCheckStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    mintEternalType(
      _mintChecks: MintCheckStruct[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    mintGiftType(
      giftTokenIds: BigNumberish[],
      mintChecks: MintCheckStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    mintNobleType(
      nobility: BigNumberish,
      signature: BytesLike,
      mintChecks: MintCheckStruct[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    mintPristineType(
      mintChecks: MintCheckStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    numBurnFromGiftAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    numBurnFromSelfAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    payableErc20(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    revealBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    setAirdropAuthority(
      _airdropAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setRevealBlockNumber(
      _revealBlockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setTreasury(
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setUltraSonicForkBlockNumber(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    splitSignature(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    sushiswap(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    ultraSonicForkBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    verifyAirdrop(
      to: string,
      nobility: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    airdropAuthority(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    externalBurnableERC721(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getAirdropHash(
      to: string,
      nobility: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isSigned(
      _address: string,
      messageHash: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    londonBurn(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    londonNeededFromGiftAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    londonNeededFromSelfAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    mintAshenType(
      tokenIds: BigNumberish[],
      _mintChecks: MintCheckStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    mintEternalType(
      _mintChecks: MintCheckStruct[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    mintGiftType(
      giftTokenIds: BigNumberish[],
      mintChecks: MintCheckStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    mintNobleType(
      nobility: BigNumberish,
      signature: BytesLike,
      mintChecks: MintCheckStruct[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    mintPristineType(
      mintChecks: MintCheckStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    numBurnFromGiftAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    numBurnFromSelfAmount(
      amount: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payableErc20(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    revealBlockNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAirdropAuthority(
      _airdropAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setRevealBlockNumber(
      _revealBlockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setTreasury(
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setUltraSonicForkBlockNumber(
      _ultraSonicForkBlockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    splitSignature(
      sig: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    sushiswap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ultraSonicForkBlockNumber(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    verifyAirdrop(
      to: string,
      nobility: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
